### ISSUE TITLE
Introduce our RestGPT

### ISSUE THREAD

**Issue by Yifan-Song793** [zjunlp/LLMAgentPapers#2]
Hi! The list is indeed a valuable reference for studying and developing LLM-powered agents.
I want to introduce our recent work: RestGPT: Connecting Large Language Models with Real-World Applications via RESTful APIs (http://arxiv.org/abs/2306.06624). In this paper, we consider a more realistic scenario, connecting LLMs with RESTful APIs, which use the commonly adopted REST software architectural style for web service development. For example, RestGPT can connect with Spotify music player and solve user queries, such as “Add Summertime Sadness by Lana Del Rey in my first playlist”. In RestGPT, several agents, i.e., planner, API selector, and executor, work together to accomplish realistic complex tasks. The code and demo of our work will be released in this month.
I would be honored if RestGPT could be considered for inclusion in your list. I believe that it would greatly benefit researchers, and developers seeking to explore the practical applications of LLMs.
Best regards!

**Comment by LesileZ** [comment]
Thank you so much for taking the time to recommend your paper for our list！
We have successfully added your paper to the list, and we truly appreciate your contribution to keeping our repository up-to-date and providing valuable information to the community.
If you have any further recommendations or questions, please feel free to share them with us. :smiley:
