### ISSUE TITLE
Consider adding AppWorld to the list

### ISSUE THREAD

**Issue by HarshTrivedi** [zjunlp/LLMAgentPapers#33]
Thanks for setting up this repository! If possible, I would like to add AppWorld to this list. I think the Benchmark section fits best.

🔗 Website: https://appworld.dev/
📄 Paper: https://arxiv.org/abs/2407.18901
🐦 Tweet: https://x.com/harsh3vedi/status/1818311843976233198
💬 Blog: https://appworld.dev/blog
🎬 Video(s): https://appworld.dev/video
🌎 Code: https://github.com/stonybrooknlp/appworld
🧭 Data (task, trajectories) explorer, playground: https://appworld.dev/task-explorer
🔍 API explorer: https://appworld.dev/api-explorer
📊 Leaderboard: https://appworld.dev/leaderboard

**TLDR**: Introduces AppWorld Engine, a high-fidelity execution environment of 9 day-to-day apps, operable via 457 APIs, populated with digital activities of 106 people living in a simulated world, and an associated benchmark of natural, diverse, and challenging autonomous agent tasks requiring rich and interactive coding.

**Comment by LesileZ** [comment]
Thank you for sharing your work on AppWorld! We've reviewed it and added it to our Benchmark section. We appreciate your contribution. The addition of the paper will surely enrich our resources. Thank you for recommending it!

**Comment by HarshTrivedi** [comment]
Great, thank you @LesileZ !!
